$(document).ready(function(){
  $("#unbuntu").click(function(){
    $("span.name").empty("span.name");
    $("span.class").empty("span.class");
    if(){
      $("div#type-face").addClass("unbuntu");
    }else{
      $("div#type-face").toggleClass("unbuntu")
    }
    $("span.name").append("unbuntu");
    $("span.class").append('<code>class="ubuntu"</code>');
  });
});
